config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :path => 'accounts'

  root 'homes#index'

  resources :homes do
    collection do
      post 'upload_image'
    end
  end

  resources :products do
    collection do
      get 'get_product'
    end
  end

  resources :merks
  resources :group_names
  resources :slides

end

app/models/group_name.rb
class GroupName < ActiveRecord::Base
  has_many :merks
end

app/models/imaging.rb
class Imaging < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/merk.rb
class Merk < ActiveRecord::Base
  mount_uploader :background, BackgroundUploader

  has_many :products
  belongs_to :group_name
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :merk
end

app/models/slide_show.rb
class SlideShow < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :reload_merk
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def reload_merk
    @groups = GroupName.all.order("index ASC")
    @slides = SlideShow.all.order("index ASC")
  end
end

app/controllers/group_names_controller.rb
class GroupNamesController < ApplicationController
  before_action :authenticate_user!
  before_filter :prepare_params, only: [:edit, :show]

  def index
    @group_names = GroupName.all
  end

  def show
  end

  def new
    @group_name = GroupName.new
  end

  def create
    group_name = GroupName.new(group_name_params)

    if group_name.save
      notice = "Group name berhasil di buat."
    else
      notice = "Group name gagal di buat. Hubungi administrator."
    end
    redirect_to group_names_path, :notice => notice
  end

  def edit
  end

  def update
    group_name = GroupName.find(params[:id])

    if group_name.update_attributes(group_name_params)
      notice = "Group Name berhasil di update."
    else
      notice = "Group Name gagal di update. Hubungi administrator."
    end
    redirect_to group_names_path, :notice => notice
  end

  def destroy
    group_name = GroupName.find(params[:id])

    if group_name.destroy
      notice = "Group Name berhasil di hapus"
    else
      notice = "Group Name gagal di hapus. hubungi administrator"
    end
    redirect_to group_names_path, :notice => notice
  end

  private

  def group_name_params
    params.require(:group_name).permit(:name, :index)
  end

  def prepare_params
    @group_name = GroupName.find(params[:id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

  def upload_image
  	imaging = Imaging.where(name: "background").first

  	if imaging
  		imaging.update_attributes(imaging_params)
  	else
	  	imaging = Imaging.new(imaging_params)
	  	imaging.name = "background"
  	end

  	if imaging.save
      notice = "Upload berhasil."
    else
      notice = "Upload gagal. Hubungi administrator."
    end
    redirect_to products_path, :notice => notice
  end

  private

  def imaging_params
    params.require(:imaging).permit(:name, :image)
  end
end

app/controllers/merks_controller.rb
class MerksController < ApplicationController
  before_action :authenticate_user!
  before_filter :prepare_params, only: [:edit, :show]

  def index
    @merks = Merk.all
  end

  def show
  end

  def new
    @merk = Merk.new
    @group_names = GroupName.all
  end

  def create
    merk = Merk.new(merk_params)

    if merk.save
      notice = "Merk berhasil di buat."
    else
      notice = "Merk gagal di buat. Hubungi administrator."
    end
    redirect_to merks_path, :notice => notice
  end

  def edit
    @group_names = GroupName.all
  end

  def update
    merk = Merk.find(params[:id])

    if merk.update_attributes(merk_params)
      notice = "Merk berhasil di update."
    else
      notice = "Merk gagal di update. Hubungi administrator."
    end
    redirect_to merks_path, :notice => notice
  end

  def destroy
    merk = Merk.find(params[:id])

    if merk.destroy
      notice = "Merk berhasil di hapus"
    else
      notice = "Merk gagal di hapus. hubungi administrator"
    end
    redirect_to merks_path, :notice => notice
  end

  private

  def merk_params
    params.require(:merk).permit(:name, :background, :group_name_id)
  end

  def prepare_params
    @merk = Merk.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :get_product]
  before_filter :prepare_params, only: [:edit, :show]

  def index
    if params[:merk_id].present?
      @products = Product.where(merk_id: params[:merk_id])
    else
      @products = Product.all
    end

    @imaging = Imaging.new
    @merks = Merk.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def get_product
    @product = Product.find(params[:id])

    respond_to do |format|
        format.js
    end
  end

  def new
    @product = Product.new
    @merks = Merk.all
  end

  def create    
    product = Product.new(product_params)

    if product.save
      notice = "Product berhasil di buat."
    else
      notice = "Product gagal di buat. Hubungi administrator."
    end
    redirect_to products_path, :notice => notice
  end

  def edit
    @merks = Merk.all
  end

  def update
    product = Product.find(params[:id])

    if product.update_attributes(product_params)
      notice = "Product berhasil di update."
    else
      notice = "Product gagal di update. Hubungi administrator."
    end
    redirect_to products_path, :notice => notice
  end

  def destroy
    product = Product.find(params[:id])

    if product.destroy
      notice = "Product berhasil di hapus"
    else
      notice = "Product gagal di hapus. hubungi administrator"
    end
    redirect_to products_path, :notice => notice
  end

  private

  def product_params
    params.require(:product).permit(:name, :merk_id, :image)
  end

  def prepare_params
    @product = Product.find(params[:id])
  end
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :authenticate_user!
  before_filter :prepare_params, only: [:edit, :show]

  def index
    @slides = SlideShow.all
  end

  def show
  end

  def new
    @slide = SlideShow.new
  end

  def create
    slide = SlideShow.new(slide_params)

    if slide.save
      notice = "slide berhasil di buat."
    else
      notice = "slide gagal di buat. Hubungi administrator."
    end
    redirect_to slides_path, :notice => notice
  end

  def edit
  end

  def update
    slide = SlideShow.find(params[:id])

    if slide.update_attributes(slide_params)
      notice = "slide berhasil di update."
    else
      notice = "slide gagal di update. Hubungi administrator."
    end
    redirect_to slides_path, :notice => notice
  end

  def destroy
    slide = SlideShow.find(params[:id])

    if slide.destroy
      notice = "slide berhasil di hapus"
    else
      notice = "slide gagal di hapus. hubungi administrator"
    end
    redirect_to slides_path, :notice => notice
  end

  private

  def slide_params
    params.require(:slide_show).permit(:image, :index)
  end

  def prepare_params
    @slide = SlideShow.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def check_class_active(controller, action)
    if params[:controller] == controller && params[:action] == action
      return true
    else
      return false
    end
  end
end

app/helpers/group_names_helper.rb
module GroupNamesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/merks_helper.rb
module MerksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
	def load_products(merk_id)
		return (Product.where(merk_id: merk_id).order("name ASC") rescue [])
	end
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/group_names/_form.html.erb
<div class="admin-content">
  <div class="container">
    <div class="row clearfix">
      <div class="col-md-12 column">
        <h1>Add Group</h1>
        <div class="row clearfix"><br>
          <%= form_for @group_name, :url => url, :html => {:class => "form-horizontal col-sm-12 col-sm-offset-1"} do |f| %>
            <div class="form-group">  
              <label class="col-sm-3 control-label">Name</label>
              <div class="col-sm-5">
                <%= f.text_field :name, :class => "col-sm-9 form-control", :placeholder => "Place name here..", :required => "" %>
              </div>
            </div>
            
            <div class="form-group">  
              <label class="col-sm-3 control-label">Index</label>
              <div class="col-sm-5">
                <%= f.text_field :index, :class => "col-sm-9 form-control", :placeholder => "Place index here..", :required => "" %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-3">
                <%= f.submit "Submit", :class => "btn btn-primary" %>&nbsp;
                <%= link_to "Cancel", group_names_path %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/group_names/edit.html.erb
<%= render "form", :url => group_name_path %>

app/views/group_names/index.html.erb
<div class="jumbotron transparent">
  <div class="container">
    <h1>Welcome <small>Admin!</small></h1>
    <p><big>Showing all group</big></p>
  </div>
</div>

<div class="jumbotron transparent blue">
  <%= link_to "Merk", merks_path, :class => "btn btn-primary right space" %>
  <%= link_to "Add new Group", new_group_name_path, :class => "btn btn-primary right space" %>
  <table class="table table-striped">
    <tr>
      <th>Name</th>
      <th>Index</th>
      <th>Action</th>
    </tr>
    <% @group_names.each do |group_name| %>
      <tr>
        <td><%= group_name.name %></td>
        <td><%= group_name.index %></td>
        <td>
          <%= link_to "Edit", edit_group_name_path(id: group_name.id), :class => "btn btn-primary" %>
          <%= link_to 'Destroy', group_name_path(id: group_name.id), :method => :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/group_names/new.html.erb
<%= render "form", :url => group_names_path %>

app/views/homes/index.html.erb

  <div id="slides">
    <% if @slides && @slides.count > 1 %>      
      <% @slides.each do |slide| %>
        <%= image_tag slide.image_url %>
      <% end %>
    <% else %>
      <% @groups.last.merks.each do |merk| %>
        <%= image_tag merk.background_url %>
      <% end %>
    <% end %>
  </div>

<div class="container">
  <div class="col-md-7">
  </div>
  <div class="col-md-4">
    <%= video_tag "grand_shyra.mp4", controls: true, width: 240 %>
  </div>
  <div class="col-md-1">
    <% video_tag "balmut_fata_imajinasi.mp4", controls: true, width: 240 %>
  </div>
</div>

<script>
  $(function() {
    $('#slides').slidesjs({
      width: 1024,
      height: 350,
      play: {
        active: true,
        auto: true,
        interval: 4000,
        swap: true
      }
    });
  });
</script>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation_links.html.erb
<nav class="navbar navbar-default transparent" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "<b style='color: red'>FATA</b>SPREI.com".html_safe, root_path, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--li class="<%#= 'active' if check_class_active('homes', 'about_us') %>"><%#= link_to "About Us", "" %></li-->
        <% if current_user %>
          <li class="<%= 'active' if check_class_active('products', 'index') %>"><%= link_to "Products", products_path %></li>
        <% end %>

        <% @groups.each do |group| %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= group.name %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <% if group.merks %>
                <% group.merks.each do |merk| %>
                  <% next if merk.products.count < 1 #|| merk.group_name != group %>
                  <li><%= link_to merk.name, product_path(id: merk.products.first.id) %></li>
                <% end %>
                <!--li class="divider"></li-->
              <% else %>
                <li><a href="#">Data Kosong</a></li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li class="divider"></li>
              <li><a href="<%= destroy_user_session_url %>" data-method="delete"><span class='glyphicon glyphicon-off red'></span> Log Out</a></li>
            </ul>
          </li>
        <% else %>
          <li><% link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>fatasprei.com</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--link rel="shortcut icon" href="../assets/favicon.png"-->
    <%
      imaging = Imaging.where(name: "background").first

      if imaging
    %>
      <style type="text/css">
        body {
        background: url(<%= imaging.image_url %>) no-repeat fixed;
        background-position: center bottom;
        background-color: #eee;
      }
      </style>
    <% end %>
  </head>
  <body>
    <%= render 'layouts/navigation_links' %>
    <%= render 'layouts/messages' %>
    <%= yield %>

  </body>
</html>

app/views/merks/_form.html.erb
<div class="admin-content">
  <div class="container">
    <div class="row clearfix">
      <div class="col-md-12 column">
        <h1>Add Merk</h1>
        <div class="row clearfix"><br>
          <%= form_for @merk, :url => url, :html => {:class => "form-horizontal col-sm-12 col-sm-offset-1"} do |f| %>
            <div class="form-group">  
              <label class="col-sm-3 control-label">Name</label>
              <div class="col-sm-5">
                <%= f.text_field :name, :class => "col-sm-9 form-control", :placeholder => "Place name here..", :required => "" %>
              </div>
            </div>
            
            <div class="form-group">  
              <label class="col-sm-3 control-label">Background</label>
              <div class="col-sm-9">
                <%= image_tag(@merk.background_url, width: "200") if @merk.background? %>
                <%= f.file_field :background %>
              </div>
            </div>

            <div class="form-group">  
              <label class="col-sm-3 control-label">Group Name</label>
              <div class="col-sm-5">
                <%= f.text_field :group_name, :class => "col-sm-9 form-control", :placeholder => "Place group here..", :required => "" %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-3">
                <%= f.submit "Submit", :class => "btn btn-primary" %>&nbsp;
                <%= link_to "Cancel", merks_path %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/merks/edit.html.erb
<%= render "form", :url => merk_path %>

app/views/merks/index.html.erb
<div class="jumbotron transparent">
  <div class="container">
    <h1>Welcome <small>Admin!</small></h1>
    <p><big>Showing all merks</big></p>
  </div>
</div>

<div class="jumbotron transparent blue">
  <%= link_to "Product", products_path, :class => "btn btn-primary right space" %>
  <%= link_to "Group", group_names_path, :class => "btn btn-primary right space" %>
  <%= link_to "Add new merk", new_merk_path, :class => "btn btn-primary right space" %>
  <table class="table table-striped">
    <tr>
      <th>Name</th>
      <th>Thumbnail</th>
      <th>Action</th>
    </tr>
    <% @merks.each do |merk| %>
      <tr>
        <td><%= merk.name %></td>
        <td><%= image_tag(merk.background.thumb.url) %></td>
        <td>
          <%= link_to "Edit", edit_merk_path(id: merk.id), :class => "btn btn-primary" %>
          <%= link_to 'Destroy', merk_path(id: merk.id), :method => :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/merks/new.html.erb
<%= render "form", :url => merks_path %>

app/views/products/_form.html.erb
<div class="admin-content">
  <div class="container">
    <div class="row clearfix">
      <div class="col-md-12 column">
        <h1>Product</h1>
        <div class="row clearfix"><br>
          <%= form_for @product, :url => url, :html => {:class => "form-horizontal col-sm-12 col-sm-offset-1"} do |f| %>
            <div class="form-group">  
              <label class="col-sm-3 control-label">Name</label>
              <div class="col-sm-5">
                <%= f.text_field :name, :class => "col-sm-9 form-control", :placeholder => "Place name here..", :required => "" %>
              </div>
            </div>

            <div class="form-group">  
              <label class="col-sm-3 control-label">Category</label>
              <div class="col-sm-5">
                <%= f.select :merk_id, options_for_select(@merks.collect{|merk| [merk.name, merk.id]}, @product.merk_id), {}, {:class => "col-sm-9 form-control"} %>
              </div>
            </div>
            
            <div class="form-group">  
              <label class="col-sm-3 control-label">Image</label>
              <div class="col-sm-9">
                <%= image_tag(@product.image_url, width: "200") if @product.image? %>
                <%= f.file_field :image %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-3">
                <%= f.submit "Submit", :class => "btn btn-primary" %>&nbsp;
                <%= link_to "Cancel", products_path %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/_image_show.html.erb
<%= image_tag(product.image_url, :class => "content_box1") %>

app/views/products/edit.html.erb
<%= render "form", :url => product_path %>

app/views/products/get_product.js.erb
$("#show_image").html("<%= escape_javascript(render partial: 'image_show', locals: { product: @product } ) %>");

app/views/products/index.html.erb
<script type="text/javascript">
  function filterUrl(id){
    location.href = '/products?merk_id='+ id;
  }
</script>

<div class="jumbotron transparent">
  <div class="container">
    <h1>Welcome <small>Admin!</small></h1>
    <p><big>Showing all products</big></p>
  </div>
</div>


<div class="jumbotron transparent blue">
  <%= form_for @imaging, :url => upload_image_homes_path, :html => {:class => "form-horizontal"} do |f| %>
    <label class="col-sm-2 control-label">Background Image</label>
    <div class="col-sm-3">
      <%= image_tag(@imaging.image_url, width: "200") if @imaging.image? %>
      <%= f.file_field :image %>
    </div>

    <div class="col-sm-offset-3">
      <%= f.submit "Upload", :class => "btn btn-primary" %>
    </div>
  <% end %>
  <%= select_tag "merk_id", options_for_select(@merks.collect{|merk| [merk.name, merk.id]}, params[:merk_id]), 
    :prompt => 'Select Filter', :class => "left form-control", :style => "width: 30%;", :onchange => "filterUrl(this.value);" %>
  <%= link_to "Slide", slides_path, :class => "btn btn-primary right space" %>
  <%= link_to "Merk", merks_path, :class => "btn btn-primary right space" %>
  <%= link_to "Add new product", new_product_path, :class => "btn btn-primary right space" %>
  <table class="table table-striped">
    <tr>
      <th>Name</th>
      <th>Merk</th>
      <th>Thumbnail</th>
      <th>Action</th>
    </tr>

    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.merk.name %></td>
        <td><%= image_tag(product.image.thumb.url) %></td>
        <td>
          <%= link_to "Edit", edit_product_path(id: product.id), :class => "btn btn-primary" %>
          <%= link_to 'Destroy', product_path(id: product.id), :method => :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/products/new.html.erb
<%= render "form", :url => products_path %>

app/views/products/show.html.erb
<style type="text/css">
  body {
  background: url(<%= @product.merk.background_url %>) no-repeat fixed;
  background-position: right bottom;
  background-color: #eee;
}
</style>
<script type="text/javascript">
  function changeImage(id){
    $.ajax({      
      url: '/products/get_product?id='+id,
      type:'get',
      data: {
      },
      success: function( data ) {
      },
      error: function( data ){
      }
    });
  }
</script>

  <div class="container">
    <!--h1><% @product.name %></h1-->
    <div id="show_image">
      <%= image_tag(@product.image_url, :class => "content_box1") %>
    </div>

    <div class="row">
      <% products = load_products(@product.merk_id) %>
      <div class="col-md-12" style="overflow: auto; height: 120px;">
        <% count = 0 %>
        <% products.each do |product| %>
        <% count += 1 %>
          <div class="content_box2">
            <%#= link_to image_tag(product.image.thumb.url), product_path(id: product.id) %>
            <%= link_to image_tag(product.image.thumb.url), "javascript:void(0);", onclick: "changeImage(#{product.id})" %>
          </div>
            <% if count == 8 %>
            <div class="clear"></div>
            <% count = 0 %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

app/views/slides/_form.html.erb
<div class="admin-content">
  <div class="container">
    <div class="row clearfix">
      <div class="col-md-12 column">
        <h1>Add Slide</h1>
        <div class="row clearfix"><br>
          <%= form_for @slide, :url => url, :html => {:class => "form-horizontal col-sm-12 col-sm-offset-1"} do |f| %>
            <div class="form-group">  
              <label class="col-sm-3 control-label">Name</label>
              <div class="col-sm-5">
                <%= f.text_field :index, :class => "col-sm-9 form-control", :placeholder => "Place index here..", :required => "" %>
              </div>
            </div>
            
            <div class="form-group">  
              <label class="col-sm-3 control-label">image</label>
              <div class="col-sm-9">
                <%= image_tag(@slide.image_url, width: "200") if @slide.image? %>
                <%= f.file_field :image %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-3">
                <%= f.submit "Submit", :class => "btn btn-primary" %>&nbsp;
                <%= link_to "Cancel", slides_path %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/slides/edit.html.erb
<%= render "form", :url => slide_path %>

app/views/slides/index.html.erb
<div class="jumbotron transparent">
  <div class="container">
    <h1>Welcome <small>Admin!</small></h1>
    <p><big>Showing all Slides</big></p>
  </div>
</div>

<div class="jumbotron transparent blue">
  <%= link_to "Add new slide", new_slide_path, :class => "btn btn-primary right space" %>
  <table class="table table-striped">
    <tr>
      <th>Index</th>
      <th>Thumbnail</th>
      <th>Action</th>
    </tr>
    <% @slides.each do |slide| %>
      <tr>
        <td><%= slide.index %></td>
        <td><%= image_tag(slide.image.thumb.url) %></td>
        <td>
          <%= link_to "Edit", edit_slide_path(id: slide.id), :class => "btn btn-primary" %>
          <%= link_to 'Destroy', slide_path(id: slide.id), :method => :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/slides/new.html.erb
<%= render "form", :url => slides_path %>